name: ruuderie.com
favicon: null
layout_spectrum: 0
typography_spectrum: 0.82088
title: 'Ruud Erie | Developer | Entrepreneur'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73411607-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecf2f2'
    - '#0c1c16'
    - '#7397a8'
    - '#946d4d'
    - '#e29e73'
  brandStrength: 0.7396734245121479
  lightness: 0.1875
  saturation: 0.5450447578914464
  rhythmicContrast: 0.25
purpose: []
