analytics:
  google: UA-73411607-1
color:
  brandColors:
    - '#154e80'
    - '#c0d2db'
    - '#00d2d9'
    - '#b95073'
    - '#e81137'
  brandStrength: 0.375
  lightness: 0.9375
  rhythmicContrast: 0.75
  saturation: 0.875
cta: {}
layout_spectrum: 0.318412
name: Official Website
opengraph: {}
purpose: []
typography_spectrum: 0.94835
