name: Official Website
favicon: null
layout_spectrum: 0.26263
typography_spectrum: 0.94835
title: '| Ruud Erie'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73411607-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#154e80'
    - '#c0d2db'
    - '#00d2d9'
    - '#b95073'
    - '#e81137'
  brandStrength: 0.375
  lightness: 0.9375
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
