name: ruuderie.com
favicon: null
layout_spectrum: 0.22967
typography_spectrum: 0.4449061013292521
title: Ruud Erie Website
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecf2f2'
    - '#0c1c16'
    - '#7397a8'
    - '#946d4d'
    - '#e29e73'
  brandStrength: 0.7396734245121479
  lightness: 0.1875
  saturation: 0.5450447578914464
  rhythmicContrast: 0.25
purpose: []
